on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: quizreg.azurecr.io
        username: ${{ secrets.acr_quizreg_username }}
        password: ${{ secrets.acr_quizreg_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/quiz-app" -f  "quiz-app/Dockerfile" -t quizreg.azurecr.io/quizapp:${{ github.sha }}
        docker push quizreg.azurecr.io/quizapp:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_quizapp_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep quizappcb77 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace quizappcb77`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: quizappcb77
        container-registry-url: quizreg.azurecr.io
        container-registry-username: ${{ secrets.acr_quizreg_username }}
        container-registry-password: ${{ secrets.acr_quizreg_password }}
        secret-name: quizappdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: quizappcb77
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          quizreg.azurecr.io/quizapp:${{ github.sha }}
        imagepullsecrets: |
          quizappdockerauth