on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n quizreg -g quizreg817b-rg --location "East US" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n quizreg --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n quizreg --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n quizreg --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: quizreg.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/quiz-app" -f  "quiz-app/Dockerfile" -t quizreg.azurecr.io/quizapp:${{ github.sha }}
        docker push quizreg.azurecr.io/quizapp:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_quizapp_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep quizappfcce | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace quizappfcce`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: quizappfcce
        container-registry-url: quizreg.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: quizappdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: quizappfcce
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          quizreg.azurecr.io/quizapp:${{ github.sha }}
        imagepullsecrets: |
          quizappdockerauth